### ISSUE TITLE
Shuffle in make_one_shot_task

### ISSUE THREAD

**Issue by utd-multimedia** [amanbasu/ECG-Authentication#3]
The "Shuffle()" in make_one_shot_task function returns an error. Are we supposed to import it some package for it or is it a implemented function? I tried shuffling the dataset with numpy and the accuracy is 18% at 3000 iterations wheras it is mentioned in the blog that the accuracy reached is 85%

**Comment by amanbasu** [comment]
The code randomly shuffles three arrays `targets`, `test_image`, and `support_set`. You can use any shuffle function, just ensure that the order within these arrays doesn't change. In simple terms, if the 'ith' index of an array moves to the 'jth' index after shuffling, it should happen for all three arrays likewise.
