### ISSUE TITLE
shuffle is not defined 

### ISSUE THREAD

**Issue by LIULIU3429** [amanbasu/ECG-Authentication#4]
shuffle is not defined ,if i  use "from import import shuffle" ,still error “shuffle() takes from 2 to 3 positional arguments but 4 were given”。
so i would like to ask how you used  the "shuffle"

**Comment by amanbasu** [comment]
You can use `np.shuffle()`

**Comment by B10610204** [comment]
![image](https://user-images.githubusercontent.com/80509622/162038407-b46c6874-eb73-4d20-b3ef-2d3fb741c7b9.png)
![image](https://user-images.githubusercontent.com/80509622/162038511-3eaccefc-148b-48bc-86a9-4926bd477c62.png)
may i ask how to fix it?

**Comment by amanbasu** [comment]
Added support for shuffle now.

```python
index = list(range(N))
np.random.shuffle(index)
targets, test_image, support_set = targets[index], test_image[index], support_set[index]
```

**Comment by B10610204** [comment]
thanks your answer
it work
