### ISSUE TITLE
Use of another database for training

### ISSUE THREAD

**Issue by Amrican10** [amanbasu/ECG-Authentication#5]
Hi Aman,

I think you are not doing filtration on ECG images because you already used filtered database (ECG-ID). So, if I am generating my own filtered ECG database (ECG images for each person) to be trained here without errors, what are the constraints (# of samples, for example) on the uploaded images?

**Comment by amanbasu** [comment]
You can train the model on any number of samples, just make sure that you change the code for splitting into train and validation sets. Also, check the input image shapes - you can either resize them to 144x224 or change the values inside the code.
