### ISSUE TITLE
how to see similarity?

### ISSUE THREAD

**Issue by B10610204** [amanbasu/ECG-Authentication#6]
![image](https://user-images.githubusercontent.com/80509622/162207915-da946a7c-9509-4163-a4bb-6185fe20d56d.png)
![image](https://user-images.githubusercontent.com/80509622/162208499-3e9ee2f4-3e2b-40ad-9ff3-0dd5c721f0e4.png)

When I predict two identical plots, the confidence is low?
Am I doing the wrong experiment?

**Comment by amanbasu** [comment]
You can try with more test samples and take the average accuracy. 
If you feel it is still low, you can also re-train the model.

**Comment by B10610204** [comment]
is that confidence means the similarity

**Comment by amanbasu** [comment]
Yes
